version: '3'

services:
  app:
    build: ./
    command: [""]
    env_file:
      - .env
    volumes:
      - .:/home/node/app:Z
    ports:
      - '9229'
    tty: true
    depends_on:
      - postgres
    networks:
      - default
      - proxy

  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odmen
      POSTGRES_PASSWORD: odmen
      POSTGRES_DB: noteapi

networks:
  proxy:
    external: true
